<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.targets', '$(MSBuildThisFileDirectory)../'))" />

  <!--
  Logic for including the ConfigurationSchema.json file and corresponding
  PackageId.targets file which brings the ConfigurationSchema.json file into the Json Schema.
  -->
  <PropertyGroup>
    <ConfigurationSchemaPath>$(MSBuildProjectDirectory)\ConfigurationSchema.json</ConfigurationSchemaPath>
    <ConfigurationSchemaExists Condition="Exists('$(ConfigurationSchemaPath)')">true</ConfigurationSchemaExists>
  </PropertyGroup>

  <ItemGroup Condition="'$(ConfigurationSchemaExists)' == 'true'">
    <None Include="$(ConfigurationSchemaPath)"
          Pack="True"
          PackagePath="ConfigurationSchema.json" />
  </ItemGroup>

  <PropertyGroup Condition="'$(ConfigurationSchemaExists)' == 'true'">
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);AddPackageTargetsInPackage</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <Target Name="AddPackageTargetsInPackage">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(MSBuildThisFileDirectory)Common\Package.targets"
                              PackagePath="buildTransitive\$(TargetFramework)\$(PackageId).targets" />
    </ItemGroup>
  </Target>

  <!--
  Logic for generating and comparing the ConfigurationSchema.json file
  -->
  <PropertyGroup>
    <TargetsTriggeredByCompilation Condition="'$(DesignTimeBuild)' != 'true'">$(TargetsTriggeredByCompilation);GenerateConfigurationSchema</TargetsTriggeredByCompilation>

    <ConfigurationSchemaGeneratorProjectPath>$(RepoRoot)src\Tools\ConfigurationSchemaGenerator\ConfigurationSchemaGenerator.csproj</ConfigurationSchemaGeneratorProjectPath>
    <ConfigurationSchemaGeneratorRspPath>$(IntermediateOutputPath)$(AsemblyName).configschema.rsp</ConfigurationSchemaGeneratorRspPath>
    <GeneratedConfigurationSchemaOutputPath>$(IntermediateOutputPath)ConfigurationSchema.json</GeneratedConfigurationSchemaOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <!-- ensure the config generator is built -->
    <ProjectReference Include="$(ConfigurationSchemaGeneratorProjectPath)"
                      Private="false"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Target Name="GenerateConfigurationSchema"
          DependsOnTargets="CoreGenerateConfigurationSchema;
                            CopyNewConfigurationSchema;
                            CompareConfigurationSchema" />

  <Target Name="WriteConfigurationSchemaGeneratorRspFile" 
    DependsOnTargets="FindReferenceAssembliesForReferences"
    Deferred="Item:ReferencePathWithRefAssemblies:r;Item:IntermediateAssembly:r;Property:GeneratedConfigurationSchemaOutputPath:r;Item:ConfigSchemaGenArg:w;Property:ConfigSchemaInput:w;Property:ConfigSchemaReferences:w;Property:ConfigSchemaOutput:w">
    <PropertyGroup>
      <ConfigSchemaInput Deferred="true">"@(IntermediateAssembly)"</ConfigSchemaInput>
      <ConfigSchemaReferences Deferred="true">"@(ReferencePathWithRefAssemblies, '" "')"</ConfigSchemaReferences>
      <ConfigSchemaOutput Deferred="true">"$(GeneratedConfigurationSchemaOutputPath)"</ConfigSchemaOutput>
    </PropertyGroup>

    <ItemGroup>
      <ConfigSchemaGenArg Deferred="true" Include="--input $(ConfigSchemaInput)" />
      <ConfigSchemaGenArg Deferred="true" Include="--reference $(ConfigSchemaReferences)" />
      <ConfigSchemaGenArg Deferred="true" Include="--output $(ConfigSchemaOutput)" />
    </ItemGroup>

    <WriteLinesToFile File="$(ConfigurationSchemaGeneratorRspPath)"
                      Lines="@(ConfigSchemaGenArg)"
                      Overwrite="true"
                      WriteOnlyWhenDifferent="true" />
  </Target>

  <Target Name="CalculateConfigurationSchemaGeneratorPath">
    <MSBuild Projects="$(ConfigurationSchemaGeneratorProjectPath)"
             Targets="GetTargetPath"
             Properties="TargetFramework=net8.0">
      <Output TaskParameter="TargetOutputs" PropertyName="ConfigurationSchemaGeneratorPath" />
    </MSBuild>
    <PropertyGroup>
      <ConfigurationSchemaGeneratorDep Condition="'$(IsPrecomputePhase)' == 'false'">$(ConfigurationSchemaGeneratorPath)</ConfigurationSchemaGeneratorDep>
      <ConfigurationSchemaGeneratorDep Condition="'$(IsPrecomputePhase)' == 'true'">$([System.IO.Path]::GetDirectoryName($(ConfigurationSchemaGeneratorPath)))\#dir</ConfigurationSchemaGeneratorDep>
    </PropertyGroup>
  </Target>

  <Target Name="CoreGenerateConfigurationSchema"
          DependsOnTargets="WriteConfigurationSchemaGeneratorRspFile;
                            CalculateConfigurationSchemaGeneratorPath"
          Inputs="$(ConfigurationSchemaGeneratorDep);
                  @(IntermediateAssembly);
                  @(IntermediateAssembly->'%(RootDir)%(Directory)%(Filename).xml');
                  @(ReferencePathPrecomputeInputs)"
          Outputs="$(GeneratedConfigurationSchemaOutputPath)"
          Deferred="Property:GeneratedConfigurationSchemaOutputPath:r;Property:ConfigurationSchemaPath:r">
    
    <ItemGroup>
      <DotNetToolDependencies Include="$(DotNetRoot)**" />
    </ItemGroup>

    <PropertyGroup>
      <GeneratorCommandLine>"$(DotNetTool)" exec "$(ConfigurationSchemaGeneratorPath)"</GeneratorCommandLine>
      <GeneratorCommandLine>$(GeneratorCommandLine) @"$(ConfigurationSchemaGeneratorRspPath)"</GeneratorCommandLine>
    </PropertyGroup>

    <Exec Command="$(GeneratorCommandLine)" PrecomputeInputs="@(DotNetToolDependencies)" />
        
    <WriteLinesToFile File="$(GeneratedConfigurationSchemaOutputPath)" Lines="{}" DeferredCondition="!Exists('$(GeneratedConfigurationSchemaOutputPath)')" />

    <ItemGroup Condition="'$(IsPrecomputePhase)' != 'true'">
      <FileWrites Include="$(GeneratedConfigurationSchemaOutputPath)" Condition="Exists('$(GeneratedConfigurationSchemaOutputPath)')"/>
    </ItemGroup>
  </Target>

  <Target Name="CopyNewConfigurationSchema"
          Condition="('$(ConfigurationSchemaExists)' != 'true' OR '$(UpdateConfigurationSchema)' == 'true')
                     AND Exists('$(GeneratedConfigurationSchemaOutputPath)')">

    <Copy SourceFiles="$(GeneratedConfigurationSchemaOutputPath)"
          DestinationFiles="$(ConfigurationSchemaPath)" />

  </Target>

  <Target Name="CompareConfigurationSchema"
    PrecomputeInputs="$(ConfigurationSchemaPath);$(GeneratedConfigurationSchemaOutputPath)"
    Deferred="Property:ConfigurationSchemaPath:r;Property:GeneratedConfigurationSchemaOutputPath:r">

    <PropertyGroup>
      <CurrentConfigurationSchemaFileContent Deferred="true">$([System.IO.File]::ReadAllText('$(ConfigurationSchemaPath)'))</CurrentConfigurationSchemaFileContent>
      <GeneratedConfigurationSchemaFileContent Deferred="true">$([System.IO.File]::ReadAllText('$(GeneratedConfigurationSchemaOutputPath)'))</GeneratedConfigurationSchemaFileContent>
    </PropertyGroup>

    <Error PrecomputationMode="Dynamic" DeferredCondition="'$(CurrentConfigurationSchemaFileContent)' != '$(GeneratedConfigurationSchemaFileContent)'"
           Text="ConfigurationSchema.json is out of date for $(MSBuildProjectFile). Run 'dotnet build --no-incremental /p:UpdateConfigurationSchema=true' to update it." />
  </Target>

</Project>
