<Project>
  <!--
    Set $(InstallBrowsersForPlaywright) to 'true' to install browsers for Playwright.
    @(BrowserForPlaywrightToInstall) is a list of browsers to install, defaulting to only `chromium`.
  -->

  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)*.cs" Link="Playwright" />

    <PackageReference Include="Microsoft.Playwright" />
  </ItemGroup>

  <Target Name="EnsureProvisionBrowsersForPlaywright" AfterTargets="Build">
    <MSBuild Projects="$(MSBuildThisFileDirectory)PlaywrightInstall.proj" RemoveProperties="TargetFramework;RuntimeIdentifier;SelfContained" />
  </Target>
</Project>
