<Project>

  <PropertyGroup>
    <!-- Enabling this rule will cause build failures on undocumented public APIs. -->
    <SkipArcadeNoWarnCS1591>true</SkipArcadeNoWarnCS1591>
    <EnablePackageValidation Condition="'$(EnablePackageValidation)' == ''">true</EnablePackageValidation>
    <PackageValidationBaselineVersion Condition="'$(EnablePackageValidation)' == 'true' and '$(PackageValidationBaselineVersion)' == ''">9.0.0</PackageValidationBaselineVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.GenAPI.Task" PrivateAssets="All" />
  </ItemGroup>

  <UsingTaskPrecomputationMode TaskName="UpdateXlf" TaskMode="Dynamic" />
  <UsingTaskPrecomputationMode TaskName="GatherXlf" TaskMode="Static" />
  <UsingTaskPrecomputationMode TaskName="GatherTranslatedSource" TaskMode="Static" />
  <UsingTaskPrecomputationMode TaskName="UpdatePackageStaticWebAssets" TaskMode="Static" />
  <UsingTaskPrecomputationMode TaskName="DiscoverDefaultScopedCssItems" TaskMode="Static" />
  <UsingTaskPrecomputationMode TaskName="TranslateSource" TaskMode="Dynamic" />
  <UsingTaskPrecomputationMode TaskName="ApplyCssScopes" TaskMode="Static" />
  <UsingTaskPrecomputationMode TaskName="ComputeCssScope" TaskMode="Static" />
  <UsingTaskPrecomputationMode TaskName="EncodeRazorInputItem" TaskMode="Static" />
  <UsingTaskPrecomputationMode TaskName="ProtoToolsPlatform" TaskMode="Static" />
  <UsingTaskPrecomputationMode TaskName="ProtoCompilerOutputs" TaskMode="Static" />
  <UsingTaskPrecomputationMode TaskName="ProtoReadDependencies" TaskMode="Static" />
  <UsingTaskPrecomputationMode TaskName="MergeConfigurationProperties" TaskMode="Static" />
  <UsingTaskPrecomputationMode TaskName="ProtoCompile" TaskMode="Dynamic" />

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
</Project>
